name: Build Rclone for Win7

on:
  repository_dispatch:
    types: [rclone-new-release]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.event.client_payload.tag }}

    steps:
      - name: Check tag
        run: |
          echo "Building rclone for tag: $TAG"

      - name: Clone rclone source
        run: |
          git clone --branch $TAG --depth 1 https://github.com/rclone/rclone.git

      - name: Download go-legacy-win7 (linux_amd64)
        run: |
          curl -fsSL https://api.github.com/repos/thongtech/go-legacy-win7/releases/latest \
          | grep browser_download_url | cut -d'"' -f4 | grep -E 'linux_amd64.tar.gz$' > go_url.txt
          GO_URL=$(cat go_url.txt)
          curl -L "$GO_URL" -o go.tar.gz
          tar -zxf go.tar.gz

      - name: Build rclone for amd64
        run: |
          mkdir -p amd64
          cd rclone
          GOOS=windows GOARCH=amd64 ../go-legacy-win7/bin/go build -trimpath -ldflags -s -tags cmount -o ../amd64/rclone-win7.exe

      - name: Build rclone for 386
        run: |
          mkdir -p 386
          cd rclone
          GOOS=windows GOARCH=386 ../go-legacy-win7/bin/go build -trimpath -ldflags -s -tags cmount -o ../386/rclone-win7.exe

      - name: Zip builds
        run: |
          zip -j rclone-${TAG}-win7-amd64.zip amd64/rclone-win7.exe
          zip -j rclone-${TAG}-win7-386.zip 386/rclone-win7.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: rclone-win7 ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: |
            rclone-${{ env.TAG }}-win7-amd64.zip
            rclone-${{ env.TAG }}-win7-386.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
